import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/eventos/1.webp',
    title: 'Fiestas',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/eventos/2.webp',
    title: 'Eventos',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/eventos/3.webp',
    title: 'Banquetes',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/eventos/4.webp',
    title: 'Musica',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/eventos/5.webp',
    title: 'Catering',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/eventos/6.webp',
    title: 'Carpas',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/eventos/7.webp',
    title: 'Comidas',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
]
